package Objects;


	public enum PlayerState {
		FORWARD,BACK,STEADYFORWARD,STEADYBACK,
		JUMPINGFORWARD,JUMPINGBACK, FALLINGFORWARD,FALLINGBACK, CROUCHINGFORWARD,CROUCHINGBACK, PREVIEW, ATTACKINGFORWARD, ATTACKINGBACK, NULL, WAITING,DEAD
	}

