package Objects;


	public enum State {
		FORWARD,BACK,STEADYFORWARD,STEADYBACK,
		JUMPINGFORWARD,JUMPINGBACK, FALLINGFORWARD,FALLINGBACK, CROUCHINGFORWARD,CROUCHINGBACK, PREVIEW, ATTACKINGFORWARD, ATTACKINGBACK, NULL, WAITING
	}

